cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

curioKenya/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('checkout/', include('checkout.urls')),
    path('cart/', include('cart.urls')),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, response
from django.core.serializers import serialize
from main.models import Product
from .cart import Cart
from django.views.decorators.csrf import csrf_exempt
import json

# @require_POST


@csrf_exempt
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST' and request.POST.get('quantity'):
        cart.add(product = product, quantity = request.POST.get(
            'quantity'), update_quantity = True)
    else:
        cart.add(product = product)

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart=Cart(request)
    cart.remove(product_id)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart=Cart(request).cart
    for cart_item in cart:
        item_from_db = Product.objects.filter(pk=cart_item).first()
        if not item_from_db:
            cart.remove(cart_item)
        else:
            cart[cart_item]['ksh_price'] = item_from_db.ksh_price
            cart[cart_item]['usd_price'] = item_from_db.usd_price
    return response.JsonResponse(cart, safe = False)

cart/templates/cart/cart.html
<div class="py-1  col-lg-4 col-md-5 col-sm-8  collapse justify-content-end position-fixed" id="cartCollapse"
    style="z-index: 1000; right: 0;">
    <div class="for-top vh-70 card bg-light shadow"
        style="width: 99%; margin:auto 1%;z-index: 1000 !important;">
        <div class="card-top d-flex">
            <div class="col">
                <span class="h5">
                    My Cart
                </span>
                <i class="fas fa-shopping-cart m-auto"></i>
            </div>

            <div class="custom-control custom-switch d-flex mx-2 btn btn-sm border bg-white">
                <input type="checkbox" class="custom-control-input position-relative" id="ksh_usd">
                <label class="custom-control-label" for="ksh_usd">USD</label>
            </div>

            <div class="font-weight-bold back-primary text-light p-1 rounded total-prc small mr-1">
                0.00
            </div>
        </div>
        <hr>
        <ol class="cart px-2 cart-items h-100 mb-0" id="cart-items">

        </ol>
        <a href="{% url 'cart_summary' %}" class="btn btn-sm btn-primary my-2 mx-auto">
            PROCEED TO CHECKOUT <i class="fas fa-cart-arrow-down"></i></a>
    </div>
</div>
<style>
    .vh-70 {
        height: 70vh !important;
        overflow-y: scroll !important;
    }

    .cart-item {
        margin: 8px 1px;
        display: grid;
        grid-template-columns: 50px 1fr;
    }
</style>

cart/templates/cart/detail.html
{% extends 'cart/base.html' %}
{% load static %}
{% block title %}
Your Shopping Cart
{% endblock %}


{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                My Shopping Order:
                <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                    {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                </a>
                {% else %}
                Your cart is empty.
                {% endif %}
                {% endwith %}
            </span>
        </h2>
        <table class="table table-striped table-hover">
            <thead style="background-color: #5AC8FA">
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit Price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product  %}
                <tr>
                    <td>
                        <a href="{{ product.get__absolute_url }}">
                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                                alt="..." style="height: 130px; width: auto">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {% csrf_token %}
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update" class="btn btn-info">
                        </form>
                    </td>
                    <td>
                        <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                    </td>
                    <td>kshs. {{ item.price }}</td>
                    <td>kshs. {{ item.total_price }}</td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                </tr>
            </tbody>
        </table>
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="btn btn-default">Continue Shopping</a>
            <a href="" class="btn btn-primary">Checkout</a>
        </p>
    </div>
</div>
{% endblock %}